name: tekartik_dtk_transformer_example_simple
version: 0.1.0
description: Simple site
dependencies:
  tekartik_dtk_transformer:
    path: ../..
dev_dependencies:
  test: any
  dev_test: any
  tekartik_pub:
    git: git://github.com/tekartik/tekartik_pub.dart

transformers:
 - tekartik_dtk_transformer/dtk_transformer
