name: tekartik_dtk_transformer
version: 0.1.0
description: Simple scss transformer
dependencies:
  tekartik_html:
    git: https://github.com/alextekartik/tekartik_html.dart
  tekartik_barback:
    git: https://github.com/alextekartik/tekartik_barback.dart
  csslib: any
dev_dependencies:
  test: any
  dev_test: any
  tekartik_pub:
    git: git://github.com/tekartik/tekartik_pub.dart
